version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql_c
    volumes:
      - ./mysql-db:/var/lib/mysql/data
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=porto_be
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - apps
  api:
    depends_on:
      - mysql
    build: ./porto-be
    container_name: api_c
    env_file: ./porto-be/.env
    ports:
      - "8080:8080"
    volumes:
      - ./porto-be:/app
    networks:
      - apps
  client:
    depends_on:
      - api
    build:
      context: ./porto-fe
      dockerfile: Dockerfile.prod
    env_file: ./porto-fe/.env.production
    container_name: client_c
    ports:
      - "4173:80"
    volumes:
      - ./porto-fe:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - apps
networks:
  apps:
    driver: "bridge"
