version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql_c
    volumes:
      - ./mysql-db:/var/lib/mysql/data
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=porto_be
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - apps
networks:
  apps:
    driver: "bridge"
